{% set version = "1.5.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fs/fs_{{ version }}.tar.gz
  sha256: 35cad1781d6d17c1feb56adc4607079c6844b63794d0ce1e74bb18dbc11e1987

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('fs')"           # [not win]
    - "\"%R%\" -e \"library('fs')\""  # [win]

about:
  home: http://fs.r-lib.org, https://github.com/r-lib/fs
  license: GPL-3.0-only
  summary: A cross-platform interface to file system operations, built on top of the 'libuv' C library.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut

# Package: fs
# Title: Cross-Platform File System Operations Based on 'libuv'
# Version: 1.2.7
# Authors@R: c( person("Jim", "Hester", email = "james.f.hester@gmail.com", role = c("aut", "cre")), person("Hadley", "Wickham", , "hadley@rstudio.com", "aut"), person("libuv project contributors", role = "cph", comment = "libuv library"), person("Joyent, Inc. and other Node contributors", role = "cph", comment = "libuv library"), person("RStudio", role = c("cph", "fnd")) )
# Description: A cross-platform interface to file system operations, built on top of the 'libuv' C library.
# Depends: R (>= 3.1)
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# ByteCompile: true
# LinkingTo: Rcpp
# Imports: methods, Rcpp
# SystemRequirements: GNU make
# RoxygenNote: 6.1.1
# URL: http://fs.r-lib.org, https://github.com/r-lib/fs
# BugReports: https://github.com/r-lib/fs/issues
# Copyright: file COPYRIGHTS
# Suggests: testthat, covr, pillar (>= 1.0.0), crayon, rmarkdown, knitr, withr,
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2019-03-19 18:52:57 UTC; jhester
# Author: Jim Hester [aut, cre], Hadley Wickham [aut], libuv project contributors [cph] (libuv library), Joyent, Inc. and other Node contributors [cph] (libuv library), RStudio [cph, fnd]
# Maintainer: Jim Hester <james.f.hester@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-03-19 23:20:03 UTC
